{% set name = "psy-strat" %}
{% set version = "0.1.1" %}
{% set sha256 = "ca70e62a76d87cd9539d9db3fd3f34818321465f518a4d15c4b4e3d8fbd08468" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 27]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.12  # [win]
    - psy-simple >=1.2.0
    - psyplot >=1.2.0
    - xarray !=0.13.0

test:
  requires:
    - psyplot-gui
    - pyqt >=5
  imports:
    - psy_strat
    - psy_strat.stratplot
    - psy_strat.strat_widget


about:
  home: https://github.com/Chilipp/psy-strat
  license: GPLv2
  license_family: GPL2
  license_file: LICENSE
  summary: 'Python package for creating stratigraphic diagrams'

  description: |
    This package defines a function to make a stratigraphic diagram that
    interfaces with the interactive psyplot visualization framework. It is
    especially useful to create pollen diagrams.
  doc_url: http://psy-strat.readthedocs.io/
  dev_url: https://github.com/Chilipp/psy-strat

extra:
  recipe-maintainers:
    - Chilipp
