travis:
  secure:
    BINSTAR_TOKEN: EQE5i9Rq6DXLIIA9O2fUL5UVnkErpgmrZQYBXresa0zW55HqJ2zACtJjtvYp8YOC83UO/hXyTz5K6jaF4tA5cRaGDBUgCvMrWi8t9l8kHxaqmaooyvSHR+9xQNUauJkwO7j5BvGKXWqDuufjSnhJaqoKOT06RXK751N0r227w93OAk/KfSFnCujuP9meLxj5E0OSlsqgxhwjMi9GGGrIS9ItvX4EV6v/8HrIA7vbkYuqItmPlZc2TOzuMrQ6Fz/SOKfoqjX0Titcyo2UA24s4WfOXjn7mcSDKyjNx3fUo33PYtJ+ahbYGG1Hhd4LVloaUCQrLp/LhBC2jZtWARiNMTDop+6MDCVrLNI2gwu0rorQHq15dXIgV6x6gd6kHvkeCnTV8DFFHA+khuiE+GZV1xfkMtSviC85vboTZtlWhVNj2YxgdXZI+DErxuNc4pLnbkLFXZC6wZ+5YTOrT5D7dJJhStp5CM3eyZ12jC4/fcgoNXEXgRqpEI97hMYaZYYvHh88s48I63UCED5dqEIdeu8VijbLsTEj7P8TWBYsdshFYUWQQlULsc7v7qYirluCKgDBu7AXFjZyI/kmqKhu8D1j/T2H30dJPh6XWlVHkXxcFC1zo4e3J9ga8J9I3BlFNYel5wW0Wruxpu/mxBdEtjoDEim/eI32U2KQvi04TdU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
